### ISSUE TITLE
Parent child hierachy view

### ISSUE THREAD

**Issue by kasirye** [tylernathanreed/nova-treeview#1]
Can i implement this in a parent child hierachy in the view and how can i do it

**Comment by tylernathanreed** [comment]
@kasirye Probably so.

As shown by the "Basic Syntax" section of the readme, this is a very generic component. All you need to know is how to derive your label (the clickable area to toggle the treeview) and menu (the toggleable area of the treeview).

The classes of the treeview, label, and menu are all configurable, so you can utilize this just about anywhere (i.e. it doesn't have to be used in the sidebar).

As far as a "parent-child hierarchy" goes, the implementation of that is entirely up to you, and without specific knowledge of what you're trying to do, I won't be able to explain how you can do. All I can tell you is that it's definitely possible.

**Comment by kasirye** [comment]
My challenge is that have been using lazychaser/laravel-nestedset package... 

my table structure is  id, title, _lft, _rgt, parent_id

how can i use your package from such a table to be able to achieve a category parent-child toggle treeview.

If this could be achieved in a nova:tool component, the better

Thanks.

**Comment by tylernathanreed** [comment]
@kasirye 

What you're essentially talking about is a nested component. I can refer you to this tutorial I found that covers the general concept of collapsible tree menus within Vue:

https://vuejsdevelopers.com/2017/10/23/vue-js-tree-menu-recursive-components/

This package definitely supports nested tree views, but due to the way your data will be structured (in that you can have recursive depths of arbitrary lengths), this can definitely be a little tricky.

If we start with the basic syntax of the treeview (which is shown in the readme):

```
<treeview tag="div" class="" toggle-tag="h3" toggle-class="flex items-center cursor-pointer">
  <template slot="label">
    <!-- Some label -->
  </template>

  <template slot="menu">
    <!-- Something to optionally display -->
  <template>
</treeview>
```

We essentially need to slot a treeview within a treeview.

Let's say you find a way to create a top-level "nodes" array variable, in which each element in within the array is a "node", and each "node" can have its own set of "nodes". In order to achieve this, you'll need to create a recursive component. Here's a mock-up of that:

**NestedTreeView.vue**
```
<template>
  <div class="nested-treeview-node" :style="indent">
    <treeview tag="div" class="" toggle-tag="h3" toggle-class="flex items-center cursor-pointer">
      <template slot="label">
        {{ label }}
      </template>

      <template slot="menu">
        <nested-treeview v-for="node in nodes" :nodes="node.nodes" :label="node.label" :depth="depth + 1"
      <template>
    </treeview>
  </div>
</template>
<script>
  export default {
    props: ['label', 'nodes', 'depth'],
    name: 'nested-treeview',
    computed: {
      indent() {
        return { padding-left: `${this.depth * 3}rem`; };
      }
    }
  }
</script>
```

Then you'd be able to use this new component like so:

```
<nested-treeview
  :label="node.label"
  :nodes="node.nodes"
  :depth="0"
/>
```

The first "node" variable is one that you would have to declare yourself. Here's an example of what the finished object could look like:

```
let node = {
  label: 'First Level',
  nodes: [
    {
      label: 'Second Level I',
      nodes: [
        {
          label: 'Third Level I'
        },
        {
          label: 'Third Level II',
          nodes: [
            {
              label: 'Fourth Level I'
            }
          ]
        }
      ]
    }, 
    {
      label: 'Second Level II'  
    }
  ]
}
```

It's up to you how you construct this object.

Hopefully all of this makes sense.

--

An an aside, since this is more of a "how to" than an actual issue, I'm going to close this issue. However, this doesn't mean that our conversation can't continue.

**Comment by kasirye** [comment]
Thanks @tylernathanreed ... let me read through. Thanks mate, i appreciate
